spring:
  messages:
    encoding: UTF-8
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50000MB
      max-request-size: 50000MB

server:
  servlet:
    context-path: /api/v1/testEdacy





springdoc:
  default-consumes-media-type: application/json

  swagger-ui:
    enabled: true
    path: /swagger-ui.html


projet:
  securite:
    jwtSecret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
    jwtExpiration: 86400000 # a day  avant 30
    jwtRefreshToken: 604800000 # 7 days avant 300







app:
  file:
    regex-splitter: '@##___@##'
  url:
    front: http://180.149.197.68:8082/demat-3fpt/auth/login
    reset_password: http://180.149.197.68:8082/demat-3fpt/auth/reset-password


url:
  logo:
    starterkit: http://localhost:8080/static/logo-image.png


interval: PT30S


